#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Locationator.Resource", IsApplication=true)]

namespace Locationator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int gpsRequestButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int gpsText = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BTN_SHOW_LOCATION_POINT = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int DAL_EMPTY_BODY = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int DAL_ERROR = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int DAL_ERROR_STATUS_CODE = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int DAL_RESPONSE_BODY = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int DAL_SUCCESS = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int LBL_LOCATION_INFO = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int TAG_DAL = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int TAG_GPS_POINT_PROVIDER = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int TAG_MAIN_ACTIVITY = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
